# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170303_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(blank=True, upload_to='home_item/', verbose_name='Изображение меню'),
        ),
    ]
