# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170303_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='links',
            field=models.URLField(blank=True),
        ),
    ]
