# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookBookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='home_item/', verbose_name='Изображение для лукбука')),
                ('links', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'LookBook Items',
                'verbose_name': 'LookBook Item',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
    ]
